name: Generate UI bundle
on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  generate:
    name: Generate step
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --quiet --no-progress --cache=.cache/npm
      - run: node_modules/.bin/gulp lint
      - run: node_modules/.bin/gulp bundle
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ui-bundle
          path: public/_/
      - name: Release with asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.token }}
          files: build/ui-bundle.zip
